date: 2020-08-11
title: Finally a universal carousel
summary: Just pushed react-spring-universal-carousel to npm. Now you can avoid any cumulative layout shift in SSR-ready React app
labels:
  - short form
