version: 2
jobs:

  install:
    docker:
      - image: circleci/node:9.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "yarn.lock" }}
            - root-dependencies- # fallback to using the latest cache if no exact match is found

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run:
          name: Install dev dependencies
          command: yarn install --production

      - save_cache:
          paths:
            - ./node_modules
          key: root-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules

  release:
    docker:
      - image: circleci/node:9.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: yarn ci:prerelease && yarn ci:release


workflows:
  version: 2

  on-master:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - release:
          requires:
            - install
          filters:
            branches:
              only: master

