version: 2
jobs:

  install:
    docker:
      - image: circleci/node:9.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-dependencies-{{ checksum "yarn.lock" }}
            - root-dependencies- # fallback to using the latest cache if no exact match is found

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run:
          name: Install dev dependencies
          command: yarn install --production

      - save_cache:
          paths:
            - ./node_modules
          key: root-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules

  lint:
    docker:
      - image: circleci/node:9.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linting
          command: yarn ci:lint

  e2e:
    docker:
      - image: circleci/node:9.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running Unit Tests
          command: yarn ci:test

  deploy:
    docker:
      - image: circleci/node:9.7.1
    working_directory: ~/repo/app
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: cd app && npx now

  alias:
    docker:
      - image: circleci/node:9.7.1
    working_directory: ~/repo/app
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: cd app && now alias

workflows:
  version: 2

  on-master:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
      - alias:
          requires:
            - deploy
          filters:
            branches:
              only: master



